### ISSUE TITLE
Usability suggestions and feature requests

### ISSUE THREAD

**Issue by cmatian** [Frodo45127/rpfm#102]
**Describe your problem**

I've been playing around with RPFM for a bit and I prefer it over PFM due to the Global search options (just the general filtering is nice for quickly finding tables and entities). I have a few usability suggestions that might help improve the program.

**Extra info?**

Using the latest release (1.6.1):

1. Global search is hidden away in a dialog box, so it's not immediately obvious to users that it's an option unless they read the documentation or play around with the tool. It would be helpful if this feature was expanded to include a shortcut (standard browser `ctrl + f` perhaps?) and/or make the search feature more visible in the UI. 
![image](https://user-images.githubusercontent.com/15117108/59072113-2e8cab00-8876-11e9-86fe-d742bc186641.png)

2. When you filter by folder and have it set to auto-expand, it will automatically expand the tree view, but there doesn't appear to be an option to collapse the tree view again. You have to reload the packfile. Might I suggest a toggle for this feature where clicking auto-expand will automatically collapse the files back to their original state?

Thanks for your work on RPFM, and your consideration for these suggestions! I'd love to personally contribute some code changes but my C++ is a bit rusty.

**Comment by Frodo45127** [comment]
About the suggestions, both are already there:
1. The shortcut for the Global Search is Ctrl+Shift+F when the TreeView on the left is focused, and it's tweakable from the shortcuts window.
2. The shotcuts for mass-expand/hide are Ctrl++ and Ctrl+-. Again, tweakables from the shortcuts window.
Almost every action in the menus has a shortcut asigned, and you can check/change them in the Shortcuts window, accesible from the Preferences window.
And if you're interested in contributing, there is an issue where C++ code is needed (multi-column filters for tables) because in rust you cannot subclass the QT widgets to change their behavior (and I barely know C++). Anyway, I'll close this issue, as both suggestions are already there, but feel free to re-open it if you have more doubts/suggestions.
