### ISSUE TITLE
Localisation Invalid

### ISSUE THREAD

**Issue by XuXinMing** [Frodo45127/rpfm#111]
I tried to create a new localization file, referring to the original ftl file, but it has no effect. I tried to delete all the files in the locale directory, which did not affect the interface display. I guess localization is not installed?

**Comment by Frodo45127** [comment]
The localisation is currently working. Thing is, if RPFM cannot find any valid localisation, it falls back to a hardcoded copy of the english localisation. That's why the UI didn't changed when you deleted the english file. To translate to a new language, you have to:
- Copy the `English_en.ftl` file to `thenameyouwanttoshowupinthesettings_xx.ftl`, being xx the unicode code for your language (https://www.unece.org/cefact/locode/service/location.html).
- Translate the file.
- Start RPFM, go to settings, and the new language should appear on the language list. Change it, restart the program, and see if it works.

Just keep in mind the ftl file can be easely broken by misplaced tabulations and such, so be careful with that.

**Comment by XuXinMing** [comment]
I tried many times and it still didn't work. 
The editor I used was notepad ++, and the encoding was confirmed to be utf-8. 
Changing the original English_en.ftl file and creating a new file were invalid. 
I feel that adding a '1' after & PackFile will not destroy the file. 
Maybe you need to put double quotes in the text?
I hope you can provide sample files in other languages. thank!

**Comment by Frodo45127** [comment]
no, the text don't need double quotes. Can you upload here the file you're trying to use so I can see what's causing it not to work?

**Comment by XuXinMing** [comment]
[Chinese_cn.zip](https://github.com/Frodo45127/rpfm/files/4708636/Chinese_cn.zip)
This is the localized file I modified, referenced from English_en.ftl

**Comment by Frodo45127** [comment]
Ok, just tested the file here and.... it seems there is an issue within RPFM when loading localisations from files. Haven't noticed it before because until now because the fallback localisation was the same as the only one I had.... Luckily, it's more or less easy to fix, so should be fixed for the next update.

**Comment by XuXinMing** [comment]
Thanks, RPFM is great!

**Comment by Frodo45127** [comment]
Fixed in the develop branch. Also, I tested that translation and it was working properly, so the file is ok too. The fix should come in version 2.0.1.
