### ISSUE TITLE
Cannot Save Variant Mesh Changes

### ISSUE THREAD

**Issue by GIGroundNPound** [Frodo45127/rpfm#158]
Using RPFM 2.3.4 for Warhammer 2 Total War
--Schemas are updated and checked today
--Updates checked today

I was just trying to change a variant mesh (literally just swap a helmet like I have done 100s of times), but when I tried to make the change and save it I get the following box that pops up and says:

"Error while trying to save the currently open PackFile:
Error while trying to do an IO operation. This means RPFM failed to read/write something from/to the disk." 

I have been able to edit the variant meshes before many times and have no idea what is causing the issue. Help would be appreciated! Thank you.

**Comment by Frodo45127** [comment]
If it pops up when hitting save it means what it says: its failing to write to disk whatever you're trying to write to disk. In this case, your packfile. This happens when you have another program locking the file, like if you're modding in /data and the game/assembly kit is open.

Make sure to close all other programs that may be locking it, and try to save it again.

**Comment by GIGroundNPound** [comment]
Thank you for your comment! I don't have anything open that would be causing said error other than KMM which is why I am confused. That being said, we can close this. The issue was that the file itself was compressed and thus not allowing me to process the changes I was trying to make!
