### ISSUE TITLE
errors and possible incorrect reference in character_generation_templates_tables

### ISSUE THREAD

**Issue by kingdomsdragon** [Frodo45127/rpfm#167]
This is for TW 3 Kingdoms.  I downloaded the most recent version of the program and checked for all 3 updates.

The Voiceover Actor column in character_generation_templates_tables references audio_vo_actor_groups/key.  When loading all the CA packfiles I can only find 2 that start with audio_vo_actor.  They are:

audio_vo_actor_group_tables
audio_vo_actors_tables

copying a voiceover actor from the loaded CA packfile character_generation_templates_tables into the search filter of both of those databases I find it located in the name field of audio_vo_actor_group_tables.  Having anything in the Voiceover Actor box causes an invalid reference error.

Another error appearing in character_generation_templates_tables is an invalid reference "0" in the clan name and other name columns.  The loaded CA packfile has a 0 in most of those columns (in fact, the only time there isn't a 0 in other name is for the Nanman kings and lady zhurong)

**Comment by Frodo45127** [comment]
Indeed, the character_generation_templates_tables to audio_vo_actor_group_tables reference was trying to search on the wrong column. That has been fixed with the schema update I just pushed. The other issue, the false positive on 0 value reference cell, is already fixed in the develop branch (just pushed the fix) and should be in 2.5 when it gets released next weekend.

Closing as it's fixed, and thanks for the report.
