### ISSUE TITLE
[RPFM_v3.0.5] Three Kingdoms - Possible Schema Errors

### ISSUE THREAD

**Issue by twgamer** [Frodo45127/rpfm#200]
Unable to do datacore these DBs any longer after the recent update. The game crashes.
Gets 'no reference column' blue error when those columns still exist. While my game version is actually v1.5.3, not v1.7.1 due to some old mods that I am trying to resurrect, the game's version was irrelevant before.

* custom_battle_loadouts_tables

These DB's column order is reversed or messed up after the recent update.

* character_generation_spawn_age_ranges_tables // Messed up.
* custom_battle_loadouts_to_ceos_tables // It was Loadout - Ceo. Mass copy-paste became a bit disturbing.

I will update the list if I find another crash-causing DB. The mod that I am using is overhaul one that touches almost every DBs in the game, makes checking a time-consuming work.

-----

PS. Can I ask why RPFM is unable to display Wu Kingdaissance v5.4.3 / v5.8.0's custom_battle DBs? Should be around.

**Comment by Frodo45127** [comment]
> PS. Can I ask why RPFM is unable to display Wu Kingdaissance v5.4.3 / v5.8.0's custom_battle DBs? Should be around.

Can you send me a link to those? The Wu Kingdaissance  5.8 I found on steam doesn't have any "custom_battle" db that I can find.

> Unable to do datacore these DBs any longer after the recent update. The game crashes.
> Gets 'no reference column' blue error when those columns still exist. While my game version is actually v1.5.3, not v1.7.1 due to some old mods that I am trying to resurrect, the game's version was irrelevant before.
> 
>      custom_battle_loadouts_tables
> 
> These DB's column order is reversed or messed up after the recent update.
> 
>     character_generation_spawn_age_ranges_tables // Messed up.
>     custom_battle_loadouts_to_ceos_tables // It was Loadout - Ceo. Mass copy-paste became a bit disturbing.
> 
> I will update the list if I find another crash-causing DB. The mod that I am using is overhaul one that touches almost every DBs in the game, makes checking a time-consuming work.

I'm checking those tables in the game and they look.... ok. If the mod touches almost every db, as you said, those crashes may be due to something broken/outdated with the entires of the table, not with RPFM itself. I recommend you to install the assembly kit, generate the dependencies cache, and use the diagnostic tool to check your pack. It may pickup many of the common errors that usually lead to crashes.

**Comment by twgamer** [comment]
Oh, it was the exactly same one in Steam Workshop for Wu Kingdaissance. Nevermind then, guess the mod team decided to handle the Custom Battle rules differently.

As for DBs, I was already doing what you suggested, still checking with validating (Steam's. 'I rolled back to vanilla') and making a temporary only-one-objective test mod, which touches the very same values, myself.
A testing process is, just for your information:

1. I make an empty data__ -- Now the game is emptied.
2. I begin to build a DB from the scratch.

The Rule of Might ("TROM") also uses this way to modify the game just in case if you need a reference.

**Comment by Frodo45127** [comment]
> I make an empty data__ -- Now the game is emptied.
> I begin to build a DB from the scratch.

That may be where the problem is. Deleting the entire table by datacoring with an empty table, then redoing it means anything the new update added there will be lost. The diagnostic tool should catch most of those situations but if you deleted something used somewhere else, like in the starpos,... those are not catched by the diagnostics.
