### ISSUE TITLE
Saving PackFile prevents game from loading

### ISSUE THREAD

**Issue by Diehydra** [Frodo45127/rpfm#233]
Opening data.pack and saving it (no changes made)

prevents the game from loading.  restoring backup data.pack game loads fine
(I also purchased champions of chaos DLC at same time rpfm update happened)

4.0.2

**Comment by Volcano467** [comment]
Yes, I have the same problem. Been using RPFM for years (thanks!), and today after the RPFM update I was working on my TW:Troy mod as usual, tinkering it. After I saved the packfile in the new RPFM version after a trivial usual change, the game wouldn't load with the saved packfile present.

I had to revert back to the pre-saved version of the mod packfile, and currently I am unable to make any changes because saving the file will break it.
(I am not complaining, just saying -- I can certainly take a break from modding.) ;)

Keep up the good work!  :]

**Comment by Frodo45127** [comment]
does still happen with 4.0.3? If so, can anyone of you upload a pack before and after gets broken for comparison?

**Comment by Diehydra** [comment]
> does still happen with 4.0.3? If so, can anyone of you upload a pack before and after gets broken for comparison?

4.0.3 fixed it , thank you
I was directly accessing the 7.5 gb pack file

**Comment by Frodo45127** [comment]
Closing then.
