### ISSUE TITLE
RPFM not working. Please fix.

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#234]
Sent a message earlier but its not here.
4.0.2 update crashed my RPFM version.
Great tool, only if I can use it.

**Comment by Frodo45127** [comment]
https://github.com/Frodo45127/rpfm/issues/232 Already answered there. Please, do not open duplicate issues, specially if you're providing no further information.

**Comment by magus721** [comment]
I'm not duplicating anything. Mostly just wondering why you keep breaking
the program. If I update RPFM and suddenly it doesn't work, do you want to
know about it or not?
No one is playing games here. I need a modding program that works and keeps
working. I am NOT here to bullshit you. Please respond on the forums in
kind. NOT HERE.

**Comment by Frodo45127** [comment]
1. No idea what forum are you talking about. The only one I post this tool in (very infrequently) is twcenter, and the only issue reported there is an issue that gets fixed by just reading the popup when you start the program after an update and doing what it says.
2. This issue literally has no details. "4.0.2 update crashed my RPFM version." is not details. When it crashes? What are the steps to reproduce it? If you open 2 issues with almost no details, I'll assume they're duplicates. So yes, I want to know when the program doesn't work, saying "update crashed my RPFM version" is useless to me.

**Comment by magus721** [comment]
I'm doneIt's not like I'm the only one who's ever had anything to say and I do tend to specify as I did with the kf5You can feign ignorance if I if you want to, I won't bother saying anything more about your program, fixed or brokenLikely if it gives me problems in the future, I'll just build my own.Nothing is worse than talking to someone with a pretentious attitude.ByeSent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: Frodo45127 ***@***.***> Date: 3/18/23  6:00 PM  (GMT-08:00) To: Frodo45127/rpfm ***@***.***> Cc: magus721 ***@***.***>, Author ***@***.***> Subject: Re: [Frodo45127/rpfm] RPFM not working. Please fix. (Issue #234) 

No idea what forum are you talking about. The only one I post this tool in (very infrequently) is twcenter, and the only issue reported there is an issue that gets fixed by just reading the popup when you start the program after an update and doing what it says.
This issue literally has no details. "4.0.2 update crashed my RPFM version." is not details. When it crashes? What are the steps to reproduce it? If you open 2 issues with almost no details, I'll assume they're duplicates. So yes, I want to know when the program doesn't work, saying "update crashed my RPFM version" is useless to me.
