### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#238]

**Comment by Frodo45127** [comment]
First, 4.0 was a rewrite of the +45k loc codebase over 9 months. It is expected to have more bugs than other releases, even after the 20 betas or so it had for people to test.

Second, if you think all was good until 4.0.2, you'll be surprised to know what bugs 4.0.1 fixed. 

And third, what does "KF5 dlls/widgets not translating..." means? All 3 translations shipped with the program seem to load properly (albeit with parts in english, but that's expected because while they're in the repo, I do not update them because I can't write neither russian nor chinese).

**Comment by magus721** [comment]
> First, 4.0 was a rewrite of the +45k loc codebase over 9 months. It is expected to have more bugs than other releases, even after the 20 betas or so it had for people to test.
> 
> Second, if you think all was good until 4.0.2, you'll be surprised to know what bugs 4.0.1 fixed.
> 
> And third, what does "KF5 dlls/widgets not translating..." means? All 3 translations shipped with the program seem to load properly (albeit with parts in english, but that's expected because while they're in the repo, I do not update them because I can't write neither russian nor chinese).

Well, I guess I'm stuck with the old version then. 
I wasn't having problem modding Attila with 4.0.01 or .03/.04 
The hotfix update disabled the newer version.
