### ISSUE TITLE
Animations errors causing game to crash at start up

### ISSUE THREAD

**Issue by Ding-adong** [Frodo45127/rpfm#275]
If i so much to open any animations txt file, it will add LF for no apparent reason.

I.E.

`	fragment		Archer_axe_melee_fragment		default_equipment_display = secondary_weapon`

becomes

`	fragment		Archer_axe_melee_fragment		default_equipment_display = 
secondary_weapon`

giving unrecognised keyword secondary_weapon error.

Notepad++ show that a LF was introduced. Had a backup of course and tried copy and paste the correct version and no luck.

Had to revert back to PFM 5.2.4 to fix it.

**Comment by Frodo45127** [comment]
what game?

**Comment by Ding-adong** [comment]
Sorry, Empire.

**Comment by Frodo45127** [comment]
mmm are you sure it's rpfm's fault?

I mean, LF is a unix line ending character, added when you press enter to jump to the next line. And in your example line, the only difference seems to be the extra space before secondary_weapon. If that's where the LF character has been added, 99% sure it's not due to rpfm adding it, as it doesn't add them anywhere, other that at the end of the line if it has to replace a CRLF.

Also, just checked to be sure and the empire animation_tables.txt (I assume that's the file you're checking) it's read correctly in RPFM.

**Comment by Ding-adong** [comment]
Change Settings - text editor - open/save - end of line from unix to dos/windows.

Also updated to latest version.

No longer replicate the problem and all is well. Not sure which of the above was the issue.

Consider it close now.
