### ISSUE TITLE
No RPFM Code .exe

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#283]
The older versions of RPFM used to have this and now you release new versions constantly without this key .exe. Why?
It used to be so simple to use this program and now its useless. Why would you change such a simple format. There's literally no help to get around this either? Stumped. Please help.

**Comment by magus721** [comment]
rpfm_ui.exe ... this is the .exe? Causes system error on my machine. ugh

**Comment by magus721** [comment]
Had to put it on a zip drive in order to use it... ffs LOL

**Comment by Frodo45127** [comment]
"rpfm_code.exe" was renamed to "rpfm_ui.exe" a long time ago because now there is an exe for the ui (the normal program) and an exe for the cli (for people which want to automate stuff related to packs).

No idea what "Causes system error on my machine" means. Please provide more details. Otherwise I cannot fix it if there's a problem. Also no idea what a zip drive is.

**Comment by magus721** [comment]
"System error" simply put is the fact that it won't work on my computer for
some reason and I have to put it on a thumb drive or a zip drive to use the
program. I can't use RPFM on my main drive and it's something about your
code. Mentioned all of that yesterday. So I don't really get the confusion.

I get that you change the .exe but you may want to change it because it
doesn't really work for everyone's computer, it never did for mine. I'm
just glad I found a solution.

RPFM-code .exe worked. My thing is if it worked, why change it? But I don't
get even why people do the things they do, lately, lol

Problem solved. Cheers!

**Comment by Frodo45127** [comment]
> "System error" simply put is the fact that it won't work on my computer for
some reason and I have to put it on a thumb drive or a zip drive to use the
program. I can't use RPFM on my main drive and it's something about your
code. Mentioned all of that yesterday. So I don't really get the confusion.

By that definition and level of detail (because you mentioned no detail) there's may be a problem on rpfm.... or there may be a butterfly flapping its wings and short-circuiting your pc. The confusion comes from the fact that you pretty much stated "stuff is broken, only works in a zip drive" and didn't say what is broken, what errors (if any) it gives you, any step to reproduce your problem.... not even something as basic as the OS you're using. So you're kinda asking me to read your mind and figure out a magic fix for a problem only you know. So I don't really get why you don't see the confusion. 

And rpfm-code was deprecated back in 2.0 I believe. So it's very, very outdated if you still have it.

**Comment by magus721** [comment]
I have to put your program on a thumb drive to use it. It's not rocket
science.

Otherwise, if I try to play it off my drive, I get a system error.

I think anyone can understand that.

**Comment by Frodo45127** [comment]
Yeah, but putting the program in another drive is a workaround, not a problem. The problem is that you get "system error" and you don't explain it further. "System error" to me sounds like "your specific system is complaining about something". What? Don't know, you don't say it. And it doesn't trigger on my pc, so it has to be something that either you do different, or something in your system that's different to mine. But you keep refusing to elaborate further than "system error", so no idea what might be happening on your pc.

**Comment by magus721** [comment]
DUDE...you are, either, too smart for your own good or you are an idiot
that is "mostly" competent at one thing. The thumb drive is the workaround.
Said that many times now. The problem was the fact that putting RPFM on my
computer drive and trying to run it came up as a System Error on my Desktop
and on my last Laptop. This occured, for me, after you stopped using the
older .exe and moving onto the new one and I read a few others had this
issue, as well. I have posted here many times on the issue. Can you really
be this dense? Anyway, this is no longer an issue for me. Good luck, ffs.
