### ISSUE TITLE
Wonderful tool, but easier to emulate windows version on Linux than try running natively

### ISSUE THREAD

**Issue by jpw1991** [Frodo45127/rpfm#290]
You've got a fantastic tool here and I mean no disrespect or anything like that. I just wanna voice my unfortunate experience with the native Linux build.

I run Ubuntu 22.04 and it's just not easy or nice to get the dependencies sorted for running this natively. First, there seems to be no way to install the qt stuff via apt so I had to use Qt's online installer which required an account and a gigantic download (3 or 4gb of stuff) and after I'd done that, it wanted more stuff (some KDE thing) and at that point I decided it's easier to just emulate.

Emulating it, it works in 3 seconds and I don't have to have Qt accounts and KDE stuff and all this crap clogging up my disk.

Maybe you can consider creating some kind of all-in-one solution for Linux to get around this? I notice the windows version ships with all the required DLLs and things.

**Comment by Frodo45127** [comment]
You sure you had the correct repos enabled? Qt is available in pretty much any distro's repo. Not even for development you need to install it manually on linux. And regarding kde, you don't need the whole thing. RPFM only uses a few kde components (like ktexteditor), which btw, when installing should pull qt as dependencies. Also keep in mind the executable I provide is built for arch. If you need it for another distro you may need to rebuild it against that distro's libs.

In windows the download has everything because that's how windows programs work. Ship with everything and you end up with a folder with a ton of files that are duplicated across the system.

And regarding doing the same on linux, there's no plan to do so, at least on my part. If someone wants to do a flatpak with everything included, they're free to do it, but for now I only plan to maintain the arch executable.

**Comment by jpw1991** [comment]
I'll try double checking my stuff.

Thanks for your reply & for your work on RPFM

**Comment by ggand0** [comment]
For the record, I was able to build `rpfm_ui` on Ubuntu 22.04 (kernel version 6.2.0-39-generic). I already had Qt5 but had to install extra packages to make it work.
1. Install missing dependencies
```
sudo apt-get update
# To fix the error saying qtuitools headers are missing
sudo apt-get install qttools5-dev qttools5-dev-tools
# To fix the linker error
sudo apt install libkf5completion-dev libkf5iconthemes-dev libkf5texteditor-dev libkf5xmlgui-dev libkf5widgetsaddons-dev
# To fix the `HspellDict::HSpellDict: Init failed` error (application level err)
sudo apt install hspell
```
2. Copy the assets directory to `/usr/share/`
Download the linux build zip (e.g. `rpfm-v4.3.4-x86_64-unknown-linux-gnu.tar.zst`), extract it, and copy the `usr/share/rpfm` to `/usr/share/`. This directory asset files like icon images.

3. Build & run
```
# In your cloned rpfm project dir
cargo run --bin rpfm_ui --release
```
