### ISSUE TITLE
Some questions about how you made this!

### ISSUE THREAD

**Issue by harfangk** [Frodo45127/rpfm#3]
First of all, this is an amazing work! I wish I could write something like this myself someday.

I'm curious about how you could create the [schema file](https://github.com/Frodo45127/rpfm/blob/master/schemas/schema_wh2.json) though.

I've also been looking through the game data using PFM recently, but it was rather difficult to navigate between different tables using that tool. So I started researching how I could migrate the raw xml data files provided by the Assembly Kit to a relational database for easier reference among tables. Unfortunately, I couldn't find any file that described the schema. And based on a [post](http://www.twcenter.net/forums/showthread.php?648526-How-to-update-PFM-schema) on twcenter about how to manually decode the binary data to create the schema file for PFM, I guessed that there was no readily available schema file. I thought of automatically parsing at least the xml files to build a schema of tables, but then I noticed that column names of xml files did not explicitly refer to table names. For example, the `armour` column in `land_units_tables` referred to `unit_armour_types_tables` without telling so. That meant that completely automatic parsing was impossible and that I had to look through the result to personally verify the schema. All in all, I was starting to think that this was more than I could do in my free time.

Then I saw this project and the schema file - you could guess how amazed I was! How did you create it? Could you find some kind of schema file among the binary data? Or did you personally create the entire schema by ironing out each column? Based on the git history, I guess it's more likely the latter but I'm really curious about how you did it!

**Comment by Frodo45127** [comment]
Mmmm it's actually quite simple. In the Assembly Kit dir/db there are some files prefixed as `TWaD_*`. Those files are the structure of the tables for Dave, the official database editor from the assembly kit. So I wrote a little function to use those. Basically, you need those files in one folder, all the encoded tables from `data.pack` in another folder and, for every `TWaD_` file the program finds it'll check if it has an encoded table in the other folder (there are like 1200 tables in Dave, only 850 or so in data.pack). If it have it, it gets the version of the table from his header, and creates an entry in the schema for that version of the table with the found structure.

Of course, that "structure" will not work, because most of the tables don't store the data of their columns in the same order than they are shown in Dave, and others don't store their localisation fields in them. So, after creating the schema automatically, I had to go open RPFM, create a pack with only the entire db folder from `data.pack` and, one by one, make sure it's decoded properly (no errors while decoding) and make sure every column it's in his correct place (luckily for this, you can just add random data to a table in Dave, export it and try to use it to decode in RPFM). Also, many columns are not encoded in the format they are shown in Dave, so I needed to fix the format of many columns too.

And the entire process took 8 days. The decoder view has improved a lot since then, so next time it'll take far less time to do it.... I hope.

If you are more interested in how it's done, the function for this is in `src/packedfile/db/schema_importer.rs`. It's triggered by enabling a const in the `main.rs` file and It'll prepare the tables to be added to a new schema it'll create (currently, it'll overwrite the current Warhammer 2 schema). It's far from being advanced code, just something I put together when the factorio spirit of "automate everything" kicked in.

**Comment by harfangk** [comment]
Thank you for explaining how you did it! It's pretty fascinating - I didn't even know there were TWaD_*.xml files. Those sneaky gobbos were hiding in the middle of the file list. And it must have been quite grueling to check and fix those malformated columns one by one. I was just thinking about manually working on `land_units_tables` and its dependencies, but it just felt so tedious even before I started working on it.

I have another question though - do these data structures change a lot with each patch? As I said, I'm thinking of migrating these to relational database, so I would like to know how often I would have to add/remove/rename database columns/tables!

**Comment by Frodo45127** [comment]
Mmmm not really. I can only speak for the TK patch, as it's the only one that forced me to update the schema, but there were just a few new tables (3, maybe 4) and some more with a new column, or something like that (10 or so). So no, there are not too many changes between updates. But... just curious, but why do you want another relational database? TWeaK already uses a relational database (you can even use sql in it).

**Comment by harfangk** [comment]
I want to build a multiplayer wiki website out of it, so I considered porting the data to a relational database that I can control. But since this is a wiki site, there won't be any write operation so maybe I should just parse relevant XML files and keep the data on memory and serve them.

**Comment by Frodo45127** [comment]
Ah, good luck with that then. I'll close this issue now. In case you have anything more to ask, feel free to open it again.
