### ISSUE TITLE
Support for Total War Arena

### ISSUE THREAD

**Issue by Trolldemorted** [Frodo45127/rpfm#5]
Could you also support Total War Arena?

Their .pack header says PFH5 (I assume pfh5 does not equal pfh5 if we are talking about different games?), but rpfm crashes if I drag and drop a pack file into it.

**Comment by Trolldemorted** [comment]
What makes you think they are encrypted?

Having looked at e.g. music.pack, I can see a "header length" (a little-endian u32 that appears to point to the begin of the payload) at 0x14, a "content length" (a little-endian u32 that always roughly matches the file size) at 0x28, and lots of strings indicating audio files with an u32 length field.

Another u32 length field appears to be at 0x017A, but I have no idea what it could be.

**Comment by Frodo45127** [comment]
That's the header, not the index. Look, this is the index (list of paths and their data's lenght) in Warhammer 2:
![imagen](https://user-images.githubusercontent.com/15714929/38457400-4914d81a-3a90-11e8-85b8-b04e5297634a.png)

This is the same, in Arena:
![imagen](https://user-images.githubusercontent.com/15714929/38457432-75707a72-3a90-11e8-9706-c807d36071e9.png)

 You see now why I think it's encrypted?

The `music.pack` is the only one that doesn't seem encrypted, and yet the added some extra info in the header, among other changes. So it's even different than Warhammer's PFH5.

**Comment by Trolldemorted** [comment]
I think you are indeed correct! Let's try to get that key out.

**Comment by Frodo45127** [comment]
WOW. Ok, first, good job. I had to read it multiple times and I'm still not sure I've understood everything (as I said, I never touched crypto before and I've never taken any serious programming course). 

A quick correction: an index entry consist in an `u32` (size of the data of that PackedFile) and a `String` (path of that PackedFile). Also, there is a `0x00` byte of separation between entries (similar to Attila's format which is weird, because Attila PackFile's are PFH4, not PFH5 and the format of Warhammer 2's PFH5 is different from this one). At least that's the format used by Arena's `music.pack` and by Warhammer 1 and Attila.

Also, that initial value you mention, maybe it comes from here? These bytes are new, they are not in any other Total War game:
![imagen](https://user-images.githubusercontent.com/15714929/38773761-92c34c88-4055-11e8-9907-6bdf4f2bc6a1.png)

Ok, I haven't understood it completely. First, what does this mean: "xoring it with a decreasing key (it gets decreased by one before you process an index entry) and 0x15091984". Second, how did you got that `KEY` you're using?

Sorry if these questions seems too... well, from an amateur, but apart from this project that I'm using to learn Rust, my programming experience is quite reduced.

**Comment by Trolldemorted** [comment]
I haven't got it all figured out, but here is what I found:

This is the beginning of 3.1's boot.pack:
![grafik](https://user-images.githubusercontent.com/10261186/38785051-dbad3952-411a-11e8-83a4-20f43724a84f.png)



Black is the static PFH header.
Grey is the PFH version.
Red is a bitmask. I think `1 << 7` means the index is encrypted, and `1 << 6` means the entries have the extra dword. Haven't seen a file that used `0x00` delimiters in TWA so far, maybe there is a flag in the bitmask for that too?
Orange is the amount of items in the index.
Green is the position of the 256 byte signature at the end of the file.
Blue is (in this case the encrypted) size of the first file.
Teal is the (always unencrypted) so far unidentified dword.

To decrypt the blue size, you
- substract 1 from the amount of remaining items and put it into a dword (0x00000007)
- calculate 0x00000007 ^ 0x15091873 ^ 0x00000007

so the first item's size (at least that's what I think it is) is 0xF0.

1C0 & (1 << 6) is true, so the next 4 teal bytes are not encrypted, so we skip them. Behind them the first item's path begins.

To decrypt the path, you
- take the item's file size (0xF0 in this case)
- i=0
- do until you decrypt a 0:
  - calculate ciphertext[i]^ file_size ^get_key_at(i) (0x63 in this case, aka the char `c`)
  - increase i

The first file's path is `commontextures\\default_black.dds`.

I have written a small lib that parses the header and decrypts the index, will most likely push to github&crates.io soon, but first I have to ensure it works for all twa .packs and does not panic on invalid input. Is there some sort of community-driven wiki or similar which documents the .pack file structure? I have seen from your and others' code that the header may also contain replaced files lists and other weird stuff, so it would be great to have a document containing the current state of knowledge.

Unfortunately the header is most likely even more complicated.if I understand the client correctly, 0x08-0x0B contains an identifier whether the header is extended and 0x0C-0x0F the size of the extension. Unfortunately I have not yet found the time to examine what happens with the bytes read from the extension.

I found the key by running TWA within a debugger, identifying the function that decrypts, and reconstructing it - it's just a `wchar_t*` containing that string.

**Comment by Trolldemorted** [comment]
Here we go: https://github.com/TotalWarArena-Modding/twa_unpack

**Comment by Frodo45127** [comment]
> Is there some sort of community-driven wiki or similar which documents the .pack file structure?

Sadly, nop. Most of what I know about PackFiles I learnt it by reading PFM source code, and looking with a hex editor at the PackFiles. I try to make good documentation in my code so if someone has to do what I'm doing, It has something to start with but... some parts of it are already outdated.

About that screenshot... pfff they changed the format... quite a lot. I'm not sure if they are still used for this, but to fill your screenshot: 

- 0x08-0x0B and 0x0C-0x0F: In other total war games sometimes there is a "PackFile Index", like the file index you are decoding here, but with names of PackFiles. This is used, for example, in the localisation PackFiles of dlcs, referencing in their PackFile index to the "main" localisation PackFile. Usually, 0x08-0x0B is the amount of PackFiles in that index, and 0x0C-0x0F is the lenght of the index. I'm not sure of their real use, as I've tried to change it sometimes in Warhammer with no aparent effect.
- 0x14-0x17: that's the lenght of the PackedFile index.
- 0x18-0x0B: this is usually a timestamp for when the PackFile was created, but it doesn't affect how the PackFile works. It can be left as ```00 00 00 00```.

The rest of the header is new for me too, so I have no idea of his use.

I'll check out later that lib,... god, and I though I knew how to use Rust. To be sincere, it's the first time I saw ```<<``` or ```^```...

Also, one question, is the type of the PackFile (0-4) still stored in the red bitmask? That usually defines the load order for PackFiles when starting the game.

**Comment by Frodo45127** [comment]
Usually, the structure of the packfiles (not only the headers, but anything in how the packfile is organised, only change when the "PFH" version changes. For example both Attila and Warhammer 1 uses PFH4, and both game's Packfiles have the same structure. And Warhammer 2 uses PFH5 (which, btw is completely different to Arena's PFH5 structure) and the only difference is they put a ```0x00``` byte between the size and the path of the packedfiles in the index. Also, the ```0x00``` I meant a few message before is what you call the 0-terminated String final zero. Just, I never heard that term, so I just use it as a separator for the entries.

So no, the headers only change between games, and only sometimes.

And about the Types, in other TW games the bytes ```0x04``` to ```0x07``` are just an integer, from 0 to 4 that tells the game what type the packfile is. The Types are:
- 0 => Boot: the first one to load. Usually only the ```boot.pack``` has this type.
- 1 => Release: the next one to load. This is the type of most of the PackFiles of modern TW games.
- 2 => Patch: the next one to load. Back in shogun 2 times, every patch included one of these. So the game loaded the first version released of the game's PackFiles, and then loaded the patch PackFiles after that, effectively patching the game.
- 3 => Mod: the next one to load. This is the one you have to enable in the mod loader to load. Otherwise the game will ignore it.
- 4 => Movie: the last one to load. We modders usually use it to "force" the game to load a mod always, without the Mod Manager. Don't know what was his original purpouse.

I heard older games used other types, like a "Shader" type, but I have never seen one of those.

**Comment by Trolldemorted** [comment]
Did you find anything in the header that would indicate whether this is a warhammer 2 or a twa pfh5 file?

TWA is apparently capable of loading pfh4 files, so it bugs me that it cannot load warhammer 2's pfh5 files.

If you want to use the lib I can polish it so that it does not panic on corrupted input.

**Comment by Frodo45127** [comment]
Sorry for not answering sooner. It has been a couple of... busy days. The only main difference in the header is ```0x04-0x07```. Also, I have checked attila packfiles, looking to implement support of Attila in RPFM, and this is the ```boot.pack```:
![imagen](https://user-images.githubusercontent.com/15714929/39092788-7f2c43e4-4615-11e8-9cf8-884a3d33def9.png)

It's the only special file, the rest are like Warhammer 1 Packfiles. PFM code says this is a "BootX" PackFile.

For the lib, before using it I'll like to test if it's "safe" to mod Arena. I mean, in other TW games you cannot even connect to games that have one PackFile different. Don't know what repercusions will have an extra PackFile in Arena, and I don't want people like "I've been banned from arena for using this thing, you c***!". If it's safe, sure. Otherwise, I'll see if I can use it as a "Read-only" mode.

**Comment by Frodo45127** [comment]
Ok, since today's patches in the develop branch, there is read-only support for Arena. I had to re-use part of the twa_pack_lib, as I wanted to integrate the decoding with the decoding of the rest of the PackFiles. After looking at the code.... I need to learn how to do that kind of thing. So I may ask you in the future to learn a bit, if you don't mind. Other than that, as Arena support is finally in the repo, I guess I'll finally close this.

**Comment by Trolldemorted** [comment]
👍 if you have any questions just ask!

Did you have a look at arena's tables yet?

This is the begin of the `_kv_rules_tables` file from the virtual file system:
![grafik](https://user-images.githubusercontent.com/10261186/43930374-5628e39c-9c39-11e8-94ed-25a5981b95bc.png)

Since this looks very random compared to other [tw games' tables](http://www.twcenter.net/forums/showthread.php?338014-Pack-Files-What-We-Know-So-Far), I assume the tables are encrypted as well. While prowling around _kv_rules_tables's parsing, I stumbled across this memory section:

![grafik](https://user-images.githubusercontent.com/10261186/43930420-8f859bb2-9c39-11e8-9a9b-79baa27913b7.png)
I assume that looks more like a normal table? This memory section is 10 bytes longer than the `_kv_rules_tables` file, but maybe they have been adding additional headers while decrypting/parsing.

Do you have any suggestions how we can grasp the semantics of the table, or even display the columns and rows in rpfm?

**Comment by Trolldemorted** [comment]
I have opened a dedicated tables issue (#9), lets move the table discussion there
